# config/default.yaml

defaults:
  # 1. Configuración BASE
  - data: ucophyrehab_base
  - model: baseline_rgb_resnet18
  - training: base
  - loss: mse
  
  # 2. El contenido del propio archivo default.yaml (ESTRICTAMENTE NECESARIO ANTES DE OTROS OVERRIDES)
  - _self_

  # 3. OVERRIDE DEL EXPERIMENTO:
  - experiment: base

project:
  name: "ucophyrehab_base"
  run_name: "base_run"

# NOTA: Las secciones validation, test y logging pueden quedarse si no tienen variantes.

validation:
  enabled: true
  every_n_epochs: 10

metrics: ["mae", "rmse"] # Output metrics for train, validation and test

test:
  checkpoint_epoch: 30 # n || None to use the last epoch of training
  batch_size: 8
  num_workers: 4
  device: "cuda"      # "cuda" | "cpu"

logging:
  runs_dir: "runs"
  print_every: 50

  tensorboard_log: True